
import { Lead } from './lead-types';

interface SearchResult {
  title: string;
  link: string;
  snippet: string;
}

export class LeadExtractor {
  private geminiApiKey: string;

  constructor(geminiApiKey: string) {
    this.geminiApiKey = geminiApiKey;
  }

  async extractLeadsFromResults(results: SearchResult[], criteria: any): Promise<Lead[]> {
    console.log(`🔍 Processing ${results.length} search results for lead extraction...`);
    
    const leads: Lead[] = [];
    
    // Process first 10 results to avoid hitting API limits
    for (let i = 0; i < Math.min(results.length, 10); i++) {
      const result = results[i];
      console.log(`📋 Processing result ${i + 1}: ${result.title}`);
      
      try {
        const extractedLead = await this.extractSingleLead(result, criteria);
        if (extractedLead) {
          console.log(`✅ Extracted lead: ${extractedLead.name} at ${extractedLead.company}`);
          leads.push(extractedLead);
        } else {
          console.log(`❌ No valid lead extracted from result ${i + 1}`);
        }
        
        // Rate limiting between API calls
        await new Promise(resolve => setTimeout(resolve, 1000));
      } catch (error) {
        console.error(`❌ Error extracting lead from result ${i + 1}:`, error);
      }
    }
    
    console.log(`📊 Final lead count: ${leads.length}`);
    return leads;
  }

  private async extractSingleLead(result: SearchResult, criteria: any): Promise<Lead | null> {
    const prompt = this.buildSimpleExtractionPrompt(result, criteria);
    
    try {
      console.log('🤖 Calling Gemini API for lead extraction...');
      
      const response = await fetch(`https://generativelanguage.googleapis.com/v1beta/models/gemini-pro:generateContent?key=${this.geminiApiKey}`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          contents: [{
            parts: [{
              text: prompt
            }]
          }]
        })
      });

      if (!response.ok) {
        console.error('❌ Gemini API error:', response.status);
        throw new Error(`Gemini API error: ${response.status}`);
      }

      const data = await response.json();
      const generatedText = data.candidates?.[0]?.content?.parts?.[0]?.text;
      
      if (generatedText) {
        console.log('📝 Gemini response received, parsing lead...');
        return this.parseLeadFromResponse(generatedText, result);
      } else {
        console.log('❌ No text generated by Gemini');
      }
    } catch (error) {
      console.error('❌ Error calling Gemini API:', error);
    }
    
    return null;
  }

  private buildSimpleExtractionPrompt(result: SearchResult, criteria: any): string {
    return `
Extract lead information from this search result:

Title: ${result.title}
URL: ${result.link}
Description: ${result.snippet}

Looking for: ${criteria.industry?.join(', ') || 'professionals'} in ${criteria.location?.city || 'any location'}

Extract ONLY if you can find a real person's information. Return JSON format:
{
  "name": "First Last",
  "company": "Company Name",
  "jobTitle": "Job Title",
  "email": "email@domain.com",
  "location": "City, State",
  "industry": "${criteria.industry?.[0] || 'Professional Services'}"
}

If no clear person/lead info, return: {"error": "no_lead_found"}
`;
  }

  private parseLeadFromResponse(response: string, result: SearchResult): Lead | null {
    try {
      console.log('🔍 Parsing Gemini response...');
      
      const jsonMatch = response.match(/\{[\s\S]*\}/);
      if (!jsonMatch) {
        console.log('❌ No JSON found in response');
        return null;
      }
      
      const leadData = JSON.parse(jsonMatch[0]);
      
      if (leadData.error || !leadData.name) {
        console.log('❌ No valid lead data found');
        return null;
      }
      
      const lead: Lead = {
        id: `lead-${Date.now()}-${Math.random().toString(36).substr(2, 9)}`,
        name: leadData.name,
        company: leadData.company || 'Unknown Company',
        jobTitle: leadData.jobTitle || 'Professional',
        email: leadData.email,
        phone: leadData.phone,
        location: leadData.location || 'Unknown Location',
        industry: leadData.industry || 'Professional Services',
        linkedinUrl: result.link.includes('linkedin') ? result.link : undefined,
        companySize: '10-50',
        score: 75,
        sourceUrl: result.link
      };
      
      console.log('✅ Successfully parsed lead:', lead.name);
      return lead;
    } catch (error) {
      console.error('❌ Error parsing lead response:', error);
      return null;
    }
  }
}
